DEVX-2255: Create documentation
AdobeDocs/app-builder-template-registry pull request #4
Opened 2022-05-20 14:33 UTC by AmyJZhao

## Description

Created documentation for Template Registry Github repo, validation checks, and API

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-23 23:18 UTC, roribio approved these changes

2022-05-24 22:57 UTC, slitviachenko requested changes
@AmyJZhao , I recently changed `/api/` to `/apis/` as OpenWhisk hardcodes it in a path.
Could you please replace all `/api/v1/` to `/apis/v1/`?

2022-05-24 22:57 UTC, slitviachenko commented on src/pages/guides/api/index.md
> +- Admin: is a member of an Adobe IMS organization listed in the `ADMIN_IMS_ORGANIZATIONS` environment varialble
A small typo.
```suggestion
- Admin: is a member of an Adobe IMS organization listed in the `ADMIN_IMS_ORGANIZATIONS` environment variable.
```

2022-05-24 22:57 UTC, slitviachenko commented on src/pages/guides/github/index.md
> +4. Fill in the name of the NPM package that contains the template.Include scope (e.g. @adobe/app-builder-template).
```suggestion
4. Fill in the name of the NPM package that contains the template. Include scope (e.g. @adobe/app-builder-template).
```

2022-05-24 22:57 UTC, slitviachenko commented on src/pages/index.md
> +Try the [Adobe App Builder Template Registry API](api/)   with Swagger UI. Explore, make calls, with full endpoint descriptions.
```suggestion
Try the [Adobe App Builder Template Registry API](api/) with Swagger UI. Explore, make calls, with full endpoint descriptions.
```

2022-05-24 23:05 UTC, slitviachenko requested changes
@AmyJZhao , could you please also update https://github.com/AdobeDocs/app-builder-template-registry/blob/main/src/openapi.yaml to be in sync with https://github.com/magento-eqp/aio-template-registry-api/blob/main/openapi.yaml ? I recently updated it a little bit.

2022-05-25 16:41 UTC, slitviachenko approved these changes

2022-05-25 19:19 UTC, merged